# copy over SSH keys to allow password-less log ons
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html

# run with `--ask-pass` to be able to provide an SSH password

---

- name: Get Local Hostname
  local_action: command hostname
  register: hostname
  
- name: Select key files
  set_fact:
    wsl_key_file="/home/{{ local_user | lower }}/.ssh/id_ed25519.pub"
    windows_key_file="/mnt/c/Users/{{ local_user }}/.ssh/id_ed25519.pub"

- debug:
    msg:
      - "Local Hostname : {{ hostname.stdout }}"
      - "Windows key file: {{ windows_key_file }}"
      - "WSL key file: {{ wsl_key_file }}"

- name: Set up WSL authorized SSH key
  ansible.posix.authorized_key:
    # user on remote host
    user: "{{ local_user | lower }}"
    state: present
    key: "{{ lookup('file', wsl_key_file) }}"
    comment: "{{ local_user | lower }}+wsl@{{ hostname.stdout }}"

- name: Set up 'normal' authorized SSH key
  ansible.posix.authorized_key:
    # user on remote host
    user: "{{ local_user | lower }}"
    state: present
    key: "{{ lookup('file', windows_key_file) }}"
    comment: "{{ local_user | lower }}@{{ hostname.stdout }}"
