# TODO: user is hardcoded

# see https://docs.docker.com/engine/install/ubuntu/
# see also https://github.com/do-community/ansible-playbooks/blob/master/docker_ubuntu1804/playbook.yml

- name: Setup and Configure Docker
  hosts: docker
  # hosts: all
  become: yes
  vars_prompt:
  - name: non_docker_user
    prompt: Non-docker (Remote) user
    default: william
    private: no
    unsafe: no
  roles:
    - role: docker
      # vars:
      #   non_docker_user: william
