# setup NAS drives so they are avialble on the Docker host
#
# requires separate `.smbcreditials` file

# note: hardcodes docker username


# https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html
# https://stackoverflow.com/questions/60414055/how-can-i-find-the-user-id-using-ansible-and-use-that-in-a-jinja2-template
# ansible-galaxy collection install ansible.posix

- name: Mount NAS drives for Docker use
  hosts: docker
  # hosts: all
  become: yes

  vars_prompt:
  - name: mount_local_user
    prompt: Mount (Remote) user
    default: docker
    private: no
    unsafe: no

  - name: nas_hostname
    prompt: NAS Hostname
    default: baffinisland
    private: no
    unsafe: no

  - name: samba_mount_user
    prompt: Samba Mount User
    default: docker
    private: no
    unsafe: no

  - name: samba_mount_pass
    prompt: Samba Mount Password
    # default: baffinisland
    private: yes
    unsafe: yes

  roles:
    - role: docker_nas
