# copy over SSH keys to allow password-less log ons
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html

# run with `--ask-pass` to be able to provide an SSH password

---
- name: Setup SSH keys
  hosts: all
  tasks:

    - name: Set up WSL authorized SSH key
      ansible.posix.authorized_key:
        # user on remote host
        user: william
        state: present
        key: "{{ lookup('file', '/home/william/.ssh/id_ed25519.pub') }}"

    - name: Set up 'normal' authorized SSH key
      ansible.posix.authorized_key:
        # user on remote host
        user: william
        state: present
        key: "{{ lookup('file', '/mnt/c/Users/William/.ssh/id_ed25519.pub') }}"
        comment: 'william@le-treport.lan'
