# copy over SSH keys to allow password-less log ons
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html

# run with `--ask-pass` to be able to provide an SSH password

---
- name: Setup SSH keys
  hosts: remote

  vars_prompt:
  - name: local_user
    prompt: Local (Windows) username
    default: William
    private: no
    unsafe: no

  roles:
    - role: ssh_keys
